### ISSUE TITLE
Stylesheet with poi icons breaks everything baaahhhh

### ISSUE THREAD

**Issue by souperneon** [tangrams/tangram-play#108]
https://cdn.rawgit.com/tangrams/carousel/7428d0c9dfda6299f97ba8c19076874ad04794e0/traditional.yaml

I tried to drop the above file in (without the extrude for the buildings) and it did't work
I removed lines 19-38 and 56-58 and it works!

**Comment by patriciogonzalezvivo** [comment]
Hi @souperneon, seams wasn't happy with the textures. I just fixed : ) Let me know how it goes. Thanks!
