### ISSUE TITLE
Add Pelias search plugin to the map

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#11]

**Comment by bcamper** [comment]
I think we should consider alternatives to putting the location search right on the map. In a demo context, it makes sense that the map is the backdrop of the entire viewport, and UI elements are floating on top of it.

But in a more app-like context like this one, it may not be desirable to take up precious map real estate with UI components. We may want to consider some kind of toolbar/tray/etc. that exposes options.

A fuller picture of the future UI and features would be helpful in determining the best direction here.

**Comment by bcamper** [comment]
cc @souperneon @louh

**Comment by louh** [comment]
@bcamper I've had similar thoughts over the last couple of days. We have a full-width menu bar on this, with plenty of room, and I did think that it would make a lot of sense to have a location selector / geo search that is not floating UI. We could have search / geolocation as an icon that drops down from the menu bar. Alternatively, expanding on this, it could be a generic location setting that includes search / geolocation but also some useful map shortcuts like "zoom to fit world".

**Comment by patriciogonzalezvivo** [comment]
Great ideas!

**Comment by bcamper** [comment]
This is done :)
