### ISSUE TITLE
Colorpicker: lighter colors in the widget should have a contrast with the white background

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#119]
e.g. dark border

**Comment by patriciogonzalezvivo** [comment]
We still need to figurate out what's the best way to display it... widgets on line multikeys end ups hiding text. Because is an editor over all, the priority should be on displaying text

**Comment by patriciogonzalezvivo** [comment]
I think this is done... right?

**Comment by louh** [comment]
Yeah
