### ISSUE TITLE
Color picker dot can become detached from color

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-play#120]
![screen shot 2015-07-29 at 2 16 16 pm](https://cloud.githubusercontent.com/assets/3371850/8965974/abdc7a52-35fc-11e5-8cca-70a556d69f09.png)

With the cursor in front of the 's' in 'scene', hit enter and then:

![screen shot 2015-07-29 at 2 16 37 pm](https://cloud.githubusercontent.com/assets/3371850/8965997/ce0f71f6-35fc-11e5-926e-2d794b1d2527.png)

**Comment by patriciogonzalezvivo** [comment]
Fixed!! thanks @blair1618

**Comment by blair1618** [comment]
So speedy :)

**Comment by patriciogonzalezvivo** [comment]
just for you my friend
