### ISSUE TITLE
Failure to start editor on Firefox

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-play#128]
The map appears, but the editor and other UI elements are unresponsive. Quoth the console:
```
16:18:09.563 TypeError: window.watch.printElapsed is not a function1 tangram-play.js:21261:30
```
Firefox 39

**Comment by patriciogonzalezvivo** [comment]
Thanks @blair1618, I leave the Watcher ON... that eliminates the bug, I will erase the benchmarking logs at the end of next week (I'm working on some optimization routines for the widgets).
