### ISSUE TITLE
Menu layout: new | open | save (login feature) | export | share (login feature) | help

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#13]

**Comment by patriciogonzalezvivo** [comment]
open after login should let you pick style previously saved on your account

**Comment by patriciogonzalezvivo** [comment]
open also should let you choose examples and more importantly warn you to save/export everything before changing the style

**Comment by louh** [comment]
Menu items that depend on future features (like ties to user accounts or server backend) can be included, but disabled and placed behind a debug flag for internal testing only.

**Comment by louh** [comment]
> open after login should let you pick style previously saved on your account 

I'm going to file this one on a different issue because this could be a separate feature.

In the meantime I will close this and mark it as done for now. Future menu revisions / additions should be new issues.
