### ISSUE TITLE
Edge browser renders color picker circle incorrectly.

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#134]
Why are you like this, IE
![screenshot 2015-08-04 08 09 20](https://cloud.githubusercontent.com/assets/2553268/9060367/11d02628-3a81-11e5-851b-13d9299c397d.png)

This is also in the original colorpicker, so something may have regressed in the new browser.
![screenshot 2015-08-04 08 11 17](https://cloud.githubusercontent.com/assets/2553268/9060380/2ca7e3aa-3a81-11e5-9c29-90fdf7cf1f81.png)

**Comment by patriciogonzalezvivo** [comment]
Wow what a bummer! How is the color wheel constructed? can we create it using a shader? : )

**Comment by louh** [comment]
It's a radial gradient on canvas: https://github.com/tangrams/tangram-play/blob/gh-pages/src/js/addons/widgets/ColorPickerModal.js#L243-L256

There's a bunch of alternatives we could take. One alternative might be to create the color wheel with a conic-gradient polyfill (http://leaverou.github.io/conic-gradient/) but now it's broken on Edge too. Hopefully we can just wait for bugs to be fixed (it was literally just released last week). Another alternative is to replace all the logic with a PNG. The color isn't picked by looking at the actual color on the screen. It's picked by some math determining the point's offset position on a circle. The circle could be anything.

Although if implementing in a shader is easy and solves the problem go for it :)

**Comment by louh** [comment]
Superceded by replacing the color picker.
