### ISSUE TITLE
Map: In Firefox, the map sometimes does not fully render or does not render at all on first load

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#139]
Resizing something (thus calling `map.invalidateSize()`) fixes it

**Comment by louh** [comment]
@bcamper 
There seems to be something that delays loading the map, tied to this message that Firefox is reporting: 
> : mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

This is reported in the Tangram library, not in the Tangram-Play code. Do you know what's going on here?

In the meantime I think I have fixed the map sometimes not rendering at all by (a) removing a bit of code that was adding Tangram after the window onload event (which I don't think is necessary at all, but I could be wrong) and (b) by setting a timeout and forcing the map to redraw itself after the end of the current execution queue: https://github.com/tangrams/tangram-play/blob/gh-pages/src/js/core/map.js#L42-L44 - I think it's actually desirable to leave this in place, but it seems like if we tackle the cause of the Firefox message above we can still speed this up generally.

**Comment by louh** [comment]
Blargh, tiles sometimes still not fully loading in Chrome.

**Comment by louh** [comment]
I should just cancel all this and start over, nothing is predictable

**Comment by louh** [comment]
I don't think we've seen this problem in a while. Is that true @bcamper @patriciogonzalezvivo ?

**Comment by bcamper** [comment]
I *think* this is fixed, let's close and revisit if we see something
similar again. That said, I don't use FF enough to know for sure (but have
fixed issues in Tangram that I know could cause this).

**Comment by louh** [comment]
:+1: Closing.
