### ISSUE TITLE
Auto indentation

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#167]

**Comment by louh** [comment]
@patriciogonzalezvivo Say more about what this means?

**Comment by patriciogonzalezvivo** [comment]
@bcamper was asking for a way to automatically set the indentation on new lines... by default goes to the previous indentation. And he was asking something that according to tangram's style structure can predict that you want to go up a level.
For examples after `layers:water:draw` will predict a level up into `draw`

**Comment by louh** [comment]
We might be able to do this through the CodeMirror mode's smart `indent` functionality: https://codemirror.net/doc/manual.html#indent

**Comment by louh** [comment]
How's this for a strategy:

In YAML mode, if you insert a new line and the previous line ends with no value or a pipe `|` character, assume additional indentation. Like so:

```yaml
# No value immediately after the key
this:
    # indent starts here
```

```yaml
# Value is a pipe character
multiline: |
    # indent starts here
```

If the new line follows a line with a value, then we assume that the new line is on the same indentation level as the previous value.

```yaml
thing: true
# indent starts here
```

This allows us to predict indentation without needing to know Tangram syntax or regexes.
