### ISSUE TITLE
Create anonymous gists as a save option

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#174]

**Comment by bcamper** [comment]
Just had a thought - it would be cool for us to use our screenshot functionality to attach a preview image to the gist as well :)  (Could even thumbnail it!)

**Comment by nvkelso** [comment]
+1

**Comment by louh** [comment]
Has anyone had experience sending binary data through the Gist API? Or, alternatively, the base64 string of the image? I can send in the base64 string easily enough, and GitHub detects the MIME type as "image/png" based on the filename, but it seems that it won't render the image.

API: https://api.github.com/gists/85c430f7d078395d3670b6361d67d0a0
Webpage: https://gist.github.com/anonymous/85c430f7d078395d3670b6361d67d0a0

This is an example of an image in a Gist that is displayed on the webpage: https://gist.github.com/mbostock/5503544#file-thumbnail-png

**Comment by louh** [comment]
Everything I find seems to indicate that GitHub does not support POSTing binary data through their Gist API. And when I try, I get error 422 "Unprocessable Entity" back from their server. Other people seem to confirm the experience that an image must be base64 encoded and that Gist will only store it as a string.

For the case of images that do get stored as binary, the only way to do it is to clone a gist locally and push the file that way.

**Comment by bcamper** [comment]
Hmm, well if it's not possible to add binary data to a gist via API, I can imagine a couple options:

- Leave images (and/or other resources) referenced as URLs in their original location (this should probably be an option anyway, seems like sometimes you want to copy resources, sometimes you don't?)
- Inline them as data URLs (I've tested this before with images in a scene file and it works -- anywhere a URL is expected should be able to accepted a data URL). It's definitely not as pretty or usable which is kind of a bummer, but it works.

**Comment by louh** [comment]
For this particular case I wanted to store a thumbnail / screenshot for a saved gist. We can still display the base64 ( data URL) image client side, no problem, but yeah, it just wouldn't be as pretty if you had a Gist link you wanted to share.

**Comment by louh** [comment]
It would be handy to be able to know the name of a scene (or set of scene files), rather than just the filename, which is sometimes not much more than "scene.yaml." Gists do not have a way to set the name of a bundle of files, using only the filename of its first file as a title. A scene should be able to have a "pretty" name much like how Bubble Wrap does now.

Proposal: store this kind of metadata in a `.tangramplayrc` text file within the Gist that Tangram Play can use.

**Comment by louh** [comment]
Another good bit of info to store in a `.tangramplay` meta file might be the original zoom / latlng / bounds of the view when it was saved. This is because scenes are loaded without changing the user's current view. However, let's say a scene was saved with external data sources that are location specific (e.g. trees in SF, curblines in Philadelphia). There is currently no way of being able to zoom to the most relevant view for that scene (similar to other GIS software's "zoom to extents" command) so remembering the view that the scene was previously saved at might be helpful and lead to a prompt about whether the view should be changed when a new scene is loaded.

**Comment by bcamper** [comment]
Interesting. Some of this metadata might also be beneficial in the scene file itself (scene name, authors, etc.), but it does sound like there may be Play-specific use cases that justify having an app-specific format (and I suppose you wouldn't want to require people to save even common metadata like scene name in their scene file if they don't want to, while we do want consistent/reliable data for Play).
