### ISSUE TITLE
Map coordinates can escape from toolbar

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-play#183]
![screen shot 2015-09-23 at 3 00 23 pm](https://cloud.githubusercontent.com/assets/3371850/10055427/3972e7a6-6204-11e5-967f-d2916f864c0b.png)

When the code pane is dragged far enough left, the map coordinates wrap to the next line

**Comment by louh** [comment]
Fixed https://github.com/tangrams/tangram-play/commit/7d2feea948523a8907c4a59b02ca2b0f993eb985
