### ISSUE TITLE
Handle 404s when loading non-existent files from query

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#191]

**Comment by bcamper** [comment]
Reminder :)

![screen shot 2016-04-12 at 5 09 28 pm](https://cloud.githubusercontent.com/assets/16733/14475726/63541010-00d1-11e6-98be-78a00ec131a1.png)

**Comment by louh** [comment]
@bcamper Can you give me a test URL where this is happening?

**Comment by bcamper** [comment]
Hmm, it was this one, but now I can't get it to repro (can't get it to put the HTML response contents into the editor, just get the regular error dialogue): https://tangrams.github.io/zinc-style/scene.yaml

**Comment by louh** [comment]
Handling 404s happened "by accident" as a result of enforcing the load process through a single flow and being able to catch status codes in the Fetch API. Did you see this on a cached or local version of Tangram Play?

Another thing to consider is whether GitHub does not reliably return 404 status codes...

This does raise the issue where even if we do catch 404s the application state is still in an awkward state when there's no scene file in it.

**Comment by bcamper** [comment]
Ah it could have been a problem with a local Play!
