### ISSUE TITLE
UI to load scene from URL

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#196]
We really need a UI to load a scene from a URL, putting `?style=url` on the query string isn't cutting it :)  It's a third option alongside loading a file, and a canned example.

**Comment by bcamper** [comment]
BTW we should probably change `style=` query string param to `scene=`

**Comment by louh** [comment]
:+1: had the same thought

**Comment by louh** [comment]
![openfromurl](https://cloud.githubusercontent.com/assets/2553268/10440068/49a5f660-710c-11e5-8447-8c4d5ce1887a.gif)

**Comment by bcamper** [comment]
:clap: :clap: :clapper:

**Comment by louh** [comment]
Remaining todos.
- [ ] Validate URL input
- [ ] Display useful feedback if a file cannot be found or read
- [ ] `scene` over `style` ?

**Comment by louh** [comment]
Regarding the second remaining todo item above: files that result in HTTP status codes are now handled (though there might still be work needed to humanize error messages). It is still possible to load files that are not valid Tangram YAML, but  this should be a separate issue.
