### ISSUE TITLE
Selecting the DOM of something will get you in troubles

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#203]

**Comment by patriciogonzalezvivo** [comment]
![00](https://cloud.githubusercontent.com/assets/346914/10465827/fb79b86a-71be-11e5-8ec7-530a5e946497.gif)

**Comment by patriciogonzalezvivo** [comment]
I keep selecting values of keys from the widget and the DOMs get selected... then if I press to delete it will go to the previous page and lose all the content of the editor

**Comment by patriciogonzalezvivo** [comment]
@louh can this be fixed with one of these css properties? 

```css
    z-index: 100000; 
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    pointer-events: none;
```

Happens very often and as a user I loose all the data with out warning.

**Comment by louh** [comment]
I know, it's terrible and sucky :(

If there were a really easy fix, it'd be done by now. The CSS properties you mentioned were some of the first I tried. Unfortunately, these don't work and if you need me to, I can explain why they won't; we will need to have scripts that listen for events on widgets and be able to handle things / delegate if certain conditions are detected (e.g. if a mousedown event begins on a widget and a mousemove is detected on the editor then do something, etc. etc.). The logic behind this is not something I've had time to think through yet.

**Comment by louh** [comment]
The lesson is, [always read the manual](https://codemirror.net/doc/manual.html#api) but if you don't do that, just talk to Marijn Haverbeke :)

**Comment by patriciogonzalezvivo** [comment]
Amazing! :+1:  :+1:  :+1:
