### ISSUE TITLE
Color widget & picker should work with alpha

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#222]
The color widget & picker doesn't work with color values that include alpha:

![screen shot 2015-11-05 at 12 03 53 pm](https://cloud.githubusercontent.com/assets/16733/10975545/845a5416-83b5-11e5-9440-dcfc2fbc301e.png)

![screen shot 2015-11-05 at 12 04 03 pm](https://cloud.githubusercontent.com/assets/16733/10975547/86d54ce6-83b5-11e5-81b2-5ecdb03a072a.png)

Color picker for red w/0.5 alpha:
![screen shot 2015-11-05 at 12 05 16 pm](https://cloud.githubusercontent.com/assets/16733/10975549/8a21345a-83b5-11e5-9f35-0e2e8b762a02.png)

**Comment by bcamper** [comment]
Hi - if resolved, can you link to the commit/PR where done when closing issues? Thanks.

**Comment by patriciogonzalezvivo** [comment]
https://github.com/tangrams/tangram-play/pull/223
