### ISSUE TITLE
Sections of text disappearing on big files

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#225]
When loading a big scene file like Skin and Bones (https://raw.githubusercontent.com/nvkelso/tangram-skin-and-bones/gh-pages/scene.yaml), I'm sometimes "losing" the editor content for awhile when scrolling through. The editor area goes black, though you can see faint indentation lines for tabs, so it is drawing something. You cannot click the text or otherwise interact. If you scroll above/below these chunks, you get the text back and can edit again. Unfortunately when this happens it means you can't edit the blank sections at all, since you can never access them! I'm also unable to repro reliably currently, but wanted to log the issue anyway for more investigation.

![screen shot 2015-11-06 at 1 07 42 pm](https://cloud.githubusercontent.com/assets/16733/11007621/2ac86d04-8499-11e5-97a3-bcbf58b9a7b4.png)

**Comment by patriciogonzalezvivo** [comment]
fixed definitely here: https://github.com/tangrams/tangram-play/commit/b38488e37f5e2fda216fc2e2be3f70d517abf520
