### ISSUE TITLE
Add Mapzen Default Styles to sample style list

### ISSUE THREAD

**Issue by riordan** [tangrams/tangram-play#241]
Now that we have [Skin and Bones](https://github.com/nvkelso/tangram-skin-and-bones), plus the [3 styles, 3 flavors](https://mapzen.com/blog/introducing-refill-cinnabar-and-zinc-styles-for-tangram), it would be great having these as style that are available as some of the defaults.

**Comment by nvkelso** [comment]
Yes! Though not Skin & Bones as that is dev only.

**Comment by louh** [comment]
:+1:

**Comment by patriciogonzalezvivo** [comment]
So true!! I will work on it!

**Comment by patriciogonzalezvivo** [comment]
Here is the commit https://github.com/tangrams/tangram-play/commit/7bfacac9fbdcb38bef6161d2abcc9c68af082305

It's ok adding the 9 permutations?

**Comment by patriciogonzalezvivo** [comment]
![screen shot 2015-12-10 at 10 05 09 am](https://cloud.githubusercontent.com/assets/346914/11718758/8d9c4f80-9f25-11e5-9643-3e72f4a0d061.png)
