### ISSUE TITLE
Clear style parameter from URL after editing

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#253]
It's great that we now save the contents of the editor and restore it on reload. But I now frequently have a problem where I load an example or style via URL, then make changes to that style in the editor, and then later reload the page. At that point my changes are lost, because the `style=` parameter remains on the URL, causing the original unmodified style to be re-loaded and replace the editor context.

I'm wondering if we should be clearing the `style=` parameter from the browser URL if the contents of the editor are modified.

**Comment by bcamper** [comment]
@louh what do you think of this case?

**Comment by louh** [comment]
Yes, I agree, that should go away.
