### ISSUE TITLE
Incorrect widget placement with hyphenated name

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#254]
Getting a weird split widget placement when a value has a hyphen:

<img width="469" alt="screen shot 2016-02-12 at 4 04 52 pm" src="https://cloud.githubusercontent.com/assets/16733/13021213/f3a54e08-d1a7-11e5-9564-60a2256abf50.png">

**Comment by patriciogonzalezvivo** [comment]
Solve in https://github.com/tangrams/tangram-play/commit/c2ed0295ea9ea2bda8b7073f772cf889425647ec
