### ISSUE TITLE
display raw_url with ".yaml" to gist instead of API result?

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#257]
When you save a file to gist, it displays a url to the github gist API, eg https://api.github.com/gists/f8c0a90d0db386e6502f

But the "load from url" functionality doesn't accept that link as input – it wants a link to the 'raw_url' in that response + ".yaml", eg https://gist.githubusercontent.com/anonymous/f8c0a90d0db386e6502f/raw/a60ef591917d38415c98a595cb9c13ebb662c9c7/tangram-waterline.yaml

Should the "copy to gist" dialog display the full link for copying? Or maybe the "load from url" could try to load the `raw_url` + ".yaml"?

Or maybe "save to gist" could display the link to the gist page itself? Or both?

**Comment by patriciogonzalezvivo** [comment]
Covered by https://github.com/tangrams/tangram-play/issues/233

**Comment by meetar** [comment]
:+1:
