### ISSUE TITLE
Check general color scheme

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#26]

**Comment by patriciogonzalezvivo** [comment]
@souperneon here https://github.com/tangrams/tangram-play/blob/gh-pages/css/style.css

**Comment by patriciogonzalezvivo** [comment]
Can you make the colors better?

**Comment by souperneon** [comment]
@patriciogonzalezvivo that link is broken?

**Comment by patriciogonzalezvivo** [comment]
Is a supper old issue... that's why I close it
