### ISSUE TITLE
Migrate to actual build process

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#262]
- [x] Add circle.ci for linting, testing, building and deployment
- [x] Built files are deployed to the Tangram S3 bucket, to land on http://mapzen.com/tangram/play/
- [x] Built files will no longer be committed
- [x] Default branch should be `master`
- [x] Update circle.ci deploy script to use `master` branch
- [x] A placeholder file index.html in gh-pages will redirect URLs + query strings and hashes to new location
- [ ] Built files will be removed, and scrubbed from history
- [x] Lint failures should exit with failure codes in Circle.ci
- [x] EXTRA CREDIT: Consider precog-ing Tangram Play

**Comment by patriciogonzalezvivo** [comment]
sounds awesome

**Comment by louh** [comment]
Placeholder index.html: https://github.com/tangrams/tangram-play/tree/gh-pages-redirect

**Comment by louh** [comment]
Github pages link is now forwarding. The old gh-pages branch is backed up here https://github.com/tangrams/tangram-play/tree/gh-pages-backup and it should be removed after everything is verified OK.

**Comment by louh** [comment]
The last thing on this list is "Built files will be removed, and scrubbed from history." This was a wish-list item for me, because we have numerous commits of a 4MB-ish JS file that must be completely re-written each time (you can't diff a file of that nature) and it balloons history. However, this can be potentially disruptive since we have a number of people who rely on local builds, and scrubbing history essentially demand that we also reset our local repositories. On the other hand, if we ever want to do this, now would be the time.

Thoughts? @bcamper @patriciogonzalezvivo
