### ISSUE TITLE
Some widgets that open picker modals will take 2 clicks to open

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#266]
For instance these widgets at the end of these lines, will require two clicks to open its picker modal.

![screenshot 2016-03-01 14 12 00](https://cloud.githubusercontent.com/assets/2553268/13438581/97f3e402-dfb7-11e5-992d-e8222baefc80.png)

This seems to occur when the value is enclosed by brackets, and if the cursor is not already on that line. A line like this will require 2 clicks on its widget marker to open:

```
       diffuse: [0.397, 0.526, 0.845]
```

This will behave as normal:

```
       color: white
```

**Comment by patriciogonzalezvivo** [comment]
https://github.com/tangrams/tangram-This fixs it... but disable the end of pbrackets high light play/commit/d8c02baa7695726d821926603e68a7bf9dfa242c

**Comment by louh** [comment]
Question filed to CodeMirror ^^

**Comment by patriciogonzalezvivo** [comment]
yay! you are the hero

**Comment by louh** [comment]
Response from Marijn (https://github.com/codemirror/CodeMirror/issues/3863#event-666868572):

> Sounds like you actually want handleMouseEvents: false (with your own code to preventDefault drag events).

This goes back to how we had it earlier, but we had set `handleMouseEvents: true` to prevent text selection from highlighting DOM by mistake. Basically, no easy solution. :-/

**Comment by louh** [comment]
Seems to be fixed - side effect of using React handlers, I believe, which now bypass CodeMirror's own event handling.
