### ISSUE TITLE
Picker modals should never go off the screen [regression]

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#267]
e.g.

![screenshot 2016-03-01 14 16 31](https://cloud.githubusercontent.com/assets/2553268/13438735/47bc6bfc-dfb8-11e5-9441-ed750b574265.png)

Is this supposed to handle it? https://github.com/tangrams/tangram-play/blob/f0e96dc00724f2847d42d0a88d873eb0d6b49150/src/js/addons/pickers/Picker.js#L104-L107

Previously, we were keeping UI modals from going off the screen a few ways:

1. Calculating its width and height and clamping it to a buffer zone around the edge of the viewport: https://github.com/tangrams/tangram-play/blob/bfef0d27bed5262348e26236673bb3d6e59fed6a/src/js/addons/widgets/ColorPicker.js#L61-L69
2. Just let Greensock do it: https://github.com/tangrams/tangram-play/blob/52f8012156dda5ec97db144cb99667a1b97085a4/src/js/addons/widgets/ColorPicker.js#L85-L87 (This was removing the check for viewport and modal height and width, because Greensock was doing it anyway.)

Incidentally, I would recommend either commenting or variable-izing the "magic numbers" to de-mystify them: what is 0.5? what does 30 do? what does 20 mean?

**Comment by patriciogonzalezvivo** [comment]
Solve here: Solve here https://github.com/tangrams/tangram-play/pull/279

**Comment by louh** [comment]
Closed with https://github.com/tangrams/tangram-play/pull/281
