### ISSUE TITLE
Consider adding handles for repositioning picker modals

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#268]
This was previously on the color picker (although not very discoverable) and was not re-implemented. Repositioning allowed the modal get out of the way (of, say, important code below it) or moved over the map for comparing colors.

**Comment by patriciogonzalezvivo** [comment]
Solve here https://github.com/tangrams/tangram-play/pull/279

**Comment by louh** [comment]
Closed with https://github.com/tangrams/tangram-play/pull/281
