### ISSUE TITLE
Color picker is missing internal padding [regression]

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#269]
Previously:

![screenshot 2016-03-01 14 38 05](https://cloud.githubusercontent.com/assets/2553268/13439393/67befb38-dfbb-11e5-94bb-eaacf99c8389.png)

Current:

![screenshot 2016-03-01 14 38 49](https://cloud.githubusercontent.com/assets/2553268/13439395/6a2ac8c0-dfbb-11e5-9f27-f875554901c9.png)

**Comment by patriciogonzalezvivo** [comment]
this is fixed here https://github.com/tangrams/tangram-play/commit/53e1b87cbd99e464943f9c8c58c36c455137b116

Although I don't like it : )

**Comment by louh** [comment]
Did you get rid of the padding intentionally before?

**Comment by patriciogonzalezvivo** [comment]
yes
