### ISSUE TITLE
Color picker loses "grabbiness" when cursor is outside the circle [regression]

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#270]
previously, as long as the user's mouse is held down, it will continue to update its position inside the picker if the user does not "color inside the lines" as it were:

![mar 01 2016 14 46](https://cloud.githubusercontent.com/assets/2553268/13439647/74920138-dfbc-11e5-8d53-8acfbbb4f552.gif)

currently, the user must remain precise. If the cursor is outside of the area the picker stops responding to mouse position:

![mar 01 2016 14 46b](https://cloud.githubusercontent.com/assets/2553268/13439694/ab1a861c-dfbc-11e5-9d38-c0ef3cf71c37.gif)

**Comment by patriciogonzalezvivo** [comment]
Fixed here https://github.com/tangrams/tangram-play/commit/ebeae7dee13b5319f5332af29b7acb199857c9e7
