### ISSUE TITLE
Replace XMLHttpRequest wrapper function with Fetch API

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#274]
Some of it is done in PR #275 

> Fetch API is more future-friendly, and has built in error-catching, which will allow us to either display error messages, log it, fall back, etc etc. Currently errors will be logged to the console, but there is now a way to expand how we deal with errors in the future. Our homegrown httpGet() function is a light abstraction over XMLHttpRequest but has no way to handle errors.

> Currently the only remaining instance of httpGet is when we are debouncing requests to the Mapzen Search API. The debounce function we are using does not handle Promises, so the next step is to investigate how to properly debounce functions that return Promises.

**Comment by louh** [comment]
Observed earlier today: Fetch requests for files were breaking on Precog builds.

Precog requires a cookie sent with each XHR request to verify that the sender has been authenticated. XHR sends this authentication cookie automatically. It turns out that Fetch does not automatically send credentials. 

As mentioned here (https://developers.google.com/web/updates/2015/03/introduction-to-fetch?hl=en), you can include the credentials with the request like so:

```
fetch(url, {  
  credentials: 'include'  
})
```

Note that this is only required for Precog. Whether or not these credentials exist do not affect local preview or on mapzen.com.

**Comment by patriciogonzalezvivo** [comment]
:+1:
