### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#285]

**Comment by patriciogonzalezvivo** [comment]
<img width="849" alt="screen shot 2016-03-18 at 9 20 18 am" src="https://cloud.githubusercontent.com/assets/346914/13878988/5b30e538-eceb-11e5-99d0-7f380db4655e.png">

Maybe is related to the fact that rawgit is down

**Comment by bcamper** [comment]
did you run npm install?

**Comment by patriciogonzalezvivo** [comment]
My fault! there was an update needed
<img width="968" alt="screen shot 2016-03-18 at 9 44 21 am" src="https://cloud.githubusercontent.com/assets/346914/13879488/1b4f57d0-ecee-11e5-82b8-704f999f1444.png">
