### ISSUE TITLE
OnLine Error handle

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#30]

**Comment by patriciogonzalezvivo** [comment]
@bcamper let me know when the error callback is ready

**Comment by patriciogonzalezvivo** [comment]
Beside and event for errors... It will be handy an event after the YAML parser finish reading the style. Some of the dynamically populated dropdown menus fetch values from the scene (like:```style``` and ```layers``` ) and the ```scene``` object need to have the data loaded.

**Comment by bcamper** [comment]
That one already exists, will show you when I add the error event.
