### ISSUE TITLE
Pop up a warning message when user is switching to a new style

### ISSUE THREAD

**Issue by souperneon** [tangrams/tangram-play#31]
For example:
You have NOT saved your style.
Go back and EXPORT the style if you want to keep a copy.
Are you sure you want to leave this page?
Go Back     Close Anyway

**Comment by souperneon** [comment]
@louh This is great… just one small edit I would suggest is to have the "Continue" with the check mark on the right and cancel to the left. It's more standard and we should make sure that is true for all button options (cancel on the left)

**Comment by louh** [comment]
Oh - you are right. That is a good observation. This is an easy fix and I will update it soon.
