### ISSUE TITLE
esc/enter keys to cancel/confirm "scene not saved" modal

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#312]
"Your scene has not been saved. Continue?"

**Comment by louh** [comment]
The escape key should be canceling this modal - is this not the case for you?

**Comment by meetar** [comment]
It works! Magical!

**Comment by louh** [comment]
Awesome. I've added a PR to automatically focus on the "Confirm" button on this modal so that the "Enter" key will confirm it.

**Comment by meetar** [comment]
Ooh, that's a nice trick.
