### ISSUE TITLE
Expand example gallery

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#320]
- [x] Split into sections (see #294)
- [ ] More emphasis on simple/focused examples, e.g. The Basics, Shaders, etc.

Let's open this thread up for ideas about what other example scenes should be in here.

**Comment by burritojustice** [comment]
@louh can we also add @meetar's demos as templates? They are very useful starting points.

**Comment by louh** [comment]
Probably! Unless they have custom UI. Which demos would you like?

**Comment by meetar** [comment]
Great idea - I'd also like to integrate those demos into a planned tutorials section in the documentation as well, which would also include a gallery - so Lou: let's sync up and talk strategy.

**Comment by louh** [comment]
cc @irealva

**Comment by louh** [comment]
@irealva @meetar Is this issue still relevant with Q3's focus on tutorials?

**Comment by meetar** [comment]
I do still plan to get a gallery in the docs, and ideally it would synchronize as much as possible with any Play integration… so I guess the answer depends on how that plan syncs with the Play roadmap.

**Comment by irealva** [comment]
Yeah I think this should remain open. once I finish the tutorial I think a few examples files could easily make their way into Tangram Play gallery.

**Comment by louh** [comment]
Cool, I'll reclassify this into Q3

**Comment by louh** [comment]
cc @kkowalsky

**Comment by louh** [comment]
Superceded by #640.
