### ISSUE TITLE
Lock npm package versions

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#329]
For more build consistency across machines/environments, I'd prefer to lock all npm package versions, rather than using the `^` or `~` npm options. I've had a few cases, most recently with the Leaflet 1.0 rc1 release, where patch or minor version releases caused significantly different behavior that we don't want to "upgrade" to without manual review.

**Comment by louh** [comment]
Would we want go as far as using [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap)?

**Comment by bcamper** [comment]
@dmvaldman did you look into shrinkwrap further or have any thoughts?

**Comment by louh** [comment]
I'm perfectly happy kicking the answer to this into the future if / when it becomes a concern. Just wanted to make sure I understood exactly what you meant by locking npm package versions. I can issue a PR locking just our immediate dependencies in `package.json` ASAP.

**Comment by bcamper** [comment]
Yeah that's what we've done for Tangram. Shrinkwrap sounds like it may be a
good option but I don't have the mental bandwidth to think it through right
now :)

**Comment by dmvaldman** [comment]
Sorry I didn't have my email notifications set appropriately and missed this. I think we should look into shrinkwrap if any problems emerge with dependencies of dependencies. So far it seems the simple "remove the carrot" approach is working for now.
