### ISSUE TITLE
'New' button broken (fails to load empty scene)

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#341]
I'm getting a fetch error when trying to clear the scene with the 'New' button. In console:

`tangram-play.js:146 GET https://data/scenes/empty.yaml net::ERR_NAME_NOT_RESOLVED`

**Comment by louh** [comment]
Ahhh! I had meant to test for this case (relative URLs should not have prepended schema / protocols).

**Comment by louh** [comment]
Try the precog version on this PR https://github.com/tangrams/tangram-play/pull/342
