### ISSUE TITLE
Widgets don't update

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#345]

**Comment by patriciogonzalezvivo** [comment]
![00](https://cloud.githubusercontent.com/assets/346914/14892843/b80b51ca-0d3a-11e6-9e58-7e8dd5b6c746.gif)
![01](https://cloud.githubusercontent.com/assets/346914/14892844/b812f894-0d3a-11e6-997f-77982f905465.gif)

**Comment by patriciogonzalezvivo** [comment]
- They don't update their content when the value of a node is modify by 'hand'
- They persist when a new line is add before them

**Comment by louh** [comment]
Do you think these are manifestations of the same problem, or could they be different issues?

**Comment by patriciogonzalezvivo** [comment]
I do think that. Seams like the widget stops pointing to the right node... so is not capable of updating their content... or die (self eliminate)

**Comment by louh** [comment]
I've narrowed down the cause of the problem to be in CodeMirror 5.14.0 ([CHANGELOG](https://github.com/codemirror/CodeMirror/blob/master/CHANGELOG.md#5140-2016-04-20)), which changed how `findMarks()` operated: "No longer return marks that touch but don't overlap given range." This was classified as a bugfix, meaning that we were depending on previous behavior that seemed unintended by CodeMirror. 

Our code to determine which bookmarks are affected is here: https://github.com/tangrams/tangram-play/blob/master/src/js/widgets/widgets-manager.js#L107-L117. It searches within the range of the affected YAML node,  but the bookmark is placed at the _end_ of the node, hence it "touches" the edge of the range but doesn't overlap. So `findMarks()` stopped working.

One proposal is to use [`findMarksAt()`](http://codemirror.net/doc/manual.html#findMarksAt) instead. We pass in the line and character of the end of the node to return the correct bookmark.
