### ISSUE TITLE
"Snap to next zoom" function

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#367]
Previous versions of Leaflet would snap the next integer zoom when double-clicking on the map. Newer versions always zoom by adding +1 to the current zoom (e.g. 14.5 will go to 15.5 on double-click). This is likely better behavior overall, but it is still useful/important especially for styling purposes to be able to easily view the map at integer zooms (to confirm styling rules etc.).

We should look at a way to provide this -- could be something like a "snap to next zoom" (e.g. `Math.floor(zoom + 1)` or something.

**Comment by louh** [comment]
Although it's not discoverable, it would be really easy to add a way to snap to the next zoom by shift-clicking on the zoom +/- buttons.
