### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by kkalera** [tangrams/tangram-play#368]
Hi,

When I open tangram play, the map is not displaying. See attached picture. 

![tangram-play](https://cloud.githubusercontent.com/assets/18085277/15718917/e240e0fa-282d-11e6-9357-7487524f9e9d.png)

**Comment by louh** [comment]
Hi @kkalera, thanks for the report. We just published a bug fix that should help resolve this! Would you mind trying again and letting me know if you still have a problem?

**Comment by kkalera** [comment]
Hi @louh , I just tried again and its working now. Thank you for the quick fix!
