### ISSUE TITLE
multiple highlight lines from url path

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#388]

**Comment by louh** [comment]
e.g. `?lines=12-24,120-136,145,199-201` this is what you expect, right?

**Comment by louh** [comment]
@patriciogonzalezvivo can you give me a yay or nay on the proposal? I will probably be able to add this later this week

**Comment by patriciogonzalezvivo** [comment]
YAY! 👍  👍 
Exactly what I would expect! thanks
