### ISSUE TITLE
Add a way to export an HTML snippet to use a tangram style as basemap

### ISSUE THREAD

**Issue by souperneon** [tangrams/tangram-play#389]
This can be immediately useful for someone wanting to use any of the house or stock styles that are in Play now as a basemap in their project. There is no clear way of doing that right now

If someone were to make their own style, they can download the yaml and change the URL in the HTML snippet and still have an easy way to embed a basemap in their project

Future, the snippet could be available to copy-paste from saved styles in your Mapzen account

**Comment by louh** [comment]
We did a very basic JS snippet version of this for public beta. Feedback from @rfriberg is we can use mapzen.js for this as well. Let's follow up on code snippet stuff in this issue.

**Comment by louh** [comment]
Superceded by #679
