### ISSUE TITLE
Shader error highlighting is broken

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#406]
Shader errors are no longer being highlighted by Play. Looks like a failure to find the appropriate YAML node:

![screen shot 2016-06-22 at 11 26 54 am](https://cloud.githubusercontent.com/assets/16733/16272637/884278ee-386c-11e6-88a2-74217d4adcec.png)

**Comment by louh** [comment]
Oh, good catch. Regressed when we changed how addresses are internally formatted to match how it outputs from Tangram (from using `/forward/slash/delimiters/` to `words:delimited:by:colons`).
