### ISSUE TITLE
Fix Widgets Text color in Firefox

### ISSUE THREAD

**Issue by irealva** [tangrams/tangram-play#409]
•	Dropdown widgets in the text editor have a lighter text color (and have become more unreadable) on Firefox.

**Comment by skorasaurus** [comment]
I was about to report this and included a screenshot of this; I have only confirmed this bug on Firefox 47 (ubuntu). 
![selection_070](https://cloud.githubusercontent.com/assets/955351/16546923/480bedb8-4128-11e6-8df5-c64bb6ea744b.png)

**Comment by irealva** [comment]
@skorasaurus thanks very much. We'll fix this very soon.
