### ISSUE TITLE
Handle url_params API keys

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#439]
Reference: https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/default.yaml#L11-L12

How do we suppress/ inject API keys that are specified in this way?

**Comment by louh** [comment]
via @blair1618 


> The url_params syntax has been around for a month or so. And yes, if a URL has an API key written inline and one appended by url_params then both will be present

> Which hasn't been a problem until the tile service started enforcing keys this week

> Putting the key in url_params is preferred because they won't get duplicated on imports

**Comment by blair1618** [comment]
It may also be worth raising this question with the tile service team. Maybe it wouldn't be crazy for the service to accept requests with multiple keys as long as at least one of them is valid. On the other hand, this could just serve to encourage bad practice.

**Comment by louh** [comment]
I can also see this playing out in another way - maybe Tangram itself could have the `url_params` value  override params in URLs.

In Tangram Play the specific thing to do here is to figure out if / how we suppress API keys from our "known" set of Mapzen vector-tiles keys - the idea behind that was to encourage users to sign up for their own keys instead of "borrowing" ours, but not break tiles before they do. Having a specific `url_params` option actually make it easier to inject temporary API keys (assuming we could append it to the `scene.config` object on scene refresh, rather than a man-in-the-middle injection into the source YAML), but it's now we have to check for keys in two places. And, assuming no behavior changes in the tiles service or Tangram, then it's Tangram Play's responsibility to be able to handle and surface the "Bad Request" errors. (See https://github.com/tangrams/blocks/issues/2)

**Comment by louh** [comment]
This is finally done. https://github.com/tangrams/tangram-play/pull/607
