### ISSUE TITLE
Fix widget parsing for certain color picker values

### ISSUE THREAD

**Issue by irealva** [tangrams/tangram-play#442]
Lou, the widget parsing sort of works but gives a wrong highlight color in places where a color widget is embedded in a complex filter. For example, in Patricio's Gotham style line 388 you have: 

```
oneway:
            filter: { oneway: yes }
            draw: { roads: { color: [0.397, 0.502, 0.429] } }
````
With a vector color the syntax highlighting is incorrect:
![screen shot 2016-07-06 at 10 46 39 am](https://cloud.githubusercontent.com/assets/8978670/16622247/6fa2c504-4367-11e6-854d-d5fd793a2fdb.png)

With an alpha value the widget disappears:
![screen shot 2016-07-06 at 10 47 17 am](https://cloud.githubusercontent.com/assets/8978670/16622258/78fc846e-4367-11e6-932e-b15bca9ce564.png)

**Comment by louh** [comment]
@irealva, is this considered fixed in PR #451?

**Comment by irealva** [comment]
yep!

**Comment by louh** [comment]
woohoo!
