### ISSUE TITLE
Getting duplicate source dropdown widgets

### ISSUE THREAD

**Issue by irealva** [tangrams/tangram-play#443]
Duplicate source dropdowns seem to appear when you click on the "Select" option in dropdowns, then back to a source like "OSM" or "Mapzen" and then click again on "Select".

![screen shot 2016-07-06 at 11 26 50 am](https://cloud.githubusercontent.com/assets/8978670/16623611/9d58034c-436c-11e6-8808-73a9cdfd4405.png)

![screen shot 2016-07-06 at 11 26 06 am](https://cloud.githubusercontent.com/assets/8978670/16623619/a265989a-436c-11e6-984b-060a7563a16d.png)

![screen shot 2016-07-06 at 11 25 47 am](https://cloud.githubusercontent.com/assets/8978670/16623625/a7c330a4-436c-11e6-9617-45b0f0d0eb3a.png)

**Comment by irealva** [comment]
The strange part is that it only seems to happen to the source dropdowns... not any of the other ones.

**Comment by louh** [comment]
@irealva Is this fixed in #451?

**Comment by irealva** [comment]
yes!

**Comment by louh** [comment]
nice!
