### ISSUE TITLE
Play doesn't throw some errors anymore

### ISSUE THREAD

**Issue by irealva** [tangrams/tangram-play#446]
Play doesn't seem to show the red error warnings it used to show in the past. It happens for example when you comment and uncomment the `source` element. 

Check out an old implementation where the error is thrown: [https://precog.mapzen.com/tangrams/tangram-play/pause/](https://precog.mapzen.com/tangrams/tangram-play/pause/)

![screen shot 2016-07-07 at 3 19 32 pm](https://cloud.githubusercontent.com/assets/8978670/16667749/04cff4cc-445c-11e6-8e13-6b181d9f5c79.png)

On current play: 
![screen shot 2016-07-07 at 3 19 48 pm](https://cloud.githubusercontent.com/assets/8978670/16667755/0a73d560-445c-11e6-960c-7ff68ca10b5c.png)

**Comment by irealva** [comment]
A related problem is that Tangram Play is not updating correctly for the first and last elements it seems. The map should render black when a source is commented - but in fact it still draws the last layer.

**Comment by louh** [comment]
I just tried this out on the production Tangram Play and the error is thrown when `sources` is commented out:

![screenshot 2016-07-20 19 22 54](https://cloud.githubusercontent.com/assets/2553268/17006495/54732f28-4eaf-11e6-90a2-047882450899.png)

Regarding the second comment - I'm not sure what you mean about the "first and last elements", but Tangram doesn't update if the YAML Is not parseable, so whatever was already in the map would still stay on the screen. We could try other ways of hiding the map or indicating some error state on the map if the YAML syntax is bad.

**Comment by irealva** [comment]
Cool. And I think that last line error you might have fixed with the parsing ticket that you closed yesterday lou. It might have been related, this issue that the bookmark doesn't get deleted on the last line. I'm fine closing this issue and seeing if we need it again. 

Not sure why in my version before the sources weren't throwing an error...
