### ISSUE TITLE
Widget bookmarks at the very end of a document duplicates the mark when you create a new line

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#456]
If a bookmark occurs at the very last line and character position in the document, and the user presses Enter to insert a new line, the bookmark is duplicated:

![end of line 1](https://cloud.githubusercontent.com/assets/2553268/16989027/7cff1f6e-4e60-11e6-821f-3aa9deecebfb.gif)

It MUST be the last line in the document. For instance, a trailing new line does not cause this to occur:

![end of line 2](https://cloud.githubusercontent.com/assets/2553268/16989055/9b9242e4-4e60-11e6-8554-cc20e72bfadd.gif)

Next steps: Check CodeMirror's `change` object (provided by the `editor.on('changes')` event) to see how this is reported. Next check our handling of changes to see what might cause the bookmark to dupe in this case.

**Comment by louh** [comment]
After investigation, this has to do with a bug in how existing marks are found in `getExistingMarks()` (see `widgets-manager.js`). I've improved the function with clearer logic which also solves the problem described above.

The reason why `getExistingMarks` exists is to abstract over how CodeMirror implements `findMarks` and `findMarksAt`. One must provide a line and character position objects to act as ranges to `findMarks`, but CodeMirror's implementation will fail to find marks at the edge of this range, or marks located on blank lines that are within this range. One must use `findMarksAt` to locate those marks specifically. Our implementation of `getExistingMarks` iterates through each line, calling `findMarks` and `findMarksAt` on each line, in order to account for those bugs.

**Comment by irealva** [comment]
This looks good - and it might help me solve the color palette issue too.
