### ISSUE TITLE
Float picker for GLSL shaders hides the actual number 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#462]
And is imposible to know what's going on

![screen shot 2016-07-20 at 4 04 40 pm](https://cloud.githubusercontent.com/assets/346914/17001143/c8cca190-4e93-11e6-92b0-d2235470d837.png)

**Comment by louh** [comment]
@patriciogonzalezvivo Can you please walk me through this one when you get a chance.

**Comment by patriciogonzalezvivo** [comment]
cool... if very simple thou... go to a floting number... click on it... and the new widget will apear on top of it. And you will not get to see the number any more

**Comment by louh** [comment]
Gotcha - I do have a suspicion about why this is the case -- I'll try to look into it tomorrow.

**Comment by irealva** [comment]
For now, they are also movable so you can drag the menu bar to change the position of the picker.

**Comment by patriciogonzalezvivo** [comment]
this same thing happens with the `vec2` picker... is very annoying. Makes the tweaking and adjusting painful
