### ISSUE TITLE
React Color Picker throwing Warning related to ReactCSS

### ISSUE THREAD

**Issue by irealva** [tangrams/tangram-play#466]
The warning is being cause by the following import in widget-color-box.react.js

`import { Hue, Alpha } from 'react-color/lib/components/common';`

and also from the following import in widget-color-input-fields.react.js

`import { EditableInput } from 'react-color/lib/components/common';`

Those imports themselves use ReactCSS even though our own code does not. If we were to import those files in the future we'd have to port them to ES6.

**Comment by louh** [comment]
I think this has gone away on its own!!
