### ISSUE TITLE
Smooth scroll-wheel zoom broken?

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#469]
It seems something may have regressed with smooth scroll-wheel zooming in Play. When I compare the scroll in Play to the [default demo](http://tangrams.github.io/tangram/), Play is now very stuttery. It will often freeze up and then jump forward. In standalone Tangram pages, the zooming isn't always continuously smooth (depends on scene complexity), but it's consistently a lot smoother.

We had a previous issue like this long ago, I can't remember the exact cause (I can try digging around), but I think it had to do with Leaflet/Code Mirror/Tangram stepping over each other with repaint or `requestAnimationFrame` events. I believe I solved it with some tweaks to Tangram's Leaflet scrollwheel control modifications.

We should also try upgrading Play to Leaflet 1.0 rc-2 and see if there is any difference.

**Comment by louh** [comment]
@bcamper Can you show me on your machine today?
