### ISSUE TITLE
react single float picker broken

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#471]
![00](https://cloud.githubusercontent.com/assets/346914/17185039/5cee829e-53fd-11e6-8ce1-db01e7dadb5e.gif)

**Comment by irealva** [comment]
Patricio what do you mean by broken?  I can't tell what's going on in the picture.

**Comment by patriciogonzalezvivo** [comment]
take a look to the think white line.
That should mark the 0? goes agains the flow of the movement... which is confusing
