### ISSUE TITLE
Save previous editor view & cursor and recover if previous content is loaded

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#51]

**Comment by bcamper** [comment]
Note per #126 this now applies to last editor content only.

**Comment by bcamper** [comment]
I see we're doing this now, right?

One nice addition that occurs to me as I've been testing changes a lot could be to restore the editor view/cursor to the same location as well. That's a small detail, but could make testing with frequent reloads nicer (each time I reload I need to search through the style to find the same spot again).
