### ISSUE TITLE
URL hides gist after opening

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#516]
Maybe a bug:

To reproduce: save a scene to gist, then open it through the "open a saved gist" menu option

Result: the URL navigates to the link including `?scene=` but then immediately updates the URL to one without the query string, eg `https://mapzen.com/tangram/play/#16.6246/40.70699/-74.01220`

Is this intentional? Is there another way to share a map made with a saved gist?

**Comment by louh** [comment]
Yup, it's a bug. I'll look into it this week.
