### ISSUE TITLE
widgets don't handle spaces in web color names

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#519]
eg `light blue` is interpreted as `lightblue` (the official web color name) in the editor and passed to Tangram, but not in the widgets:

<img width="212" alt="screen shot 2016-08-15 at 1 47 03 pm" src="https://cloud.githubusercontent.com/assets/459970/17673389/dc413884-62ee-11e6-8486-cc298eda2f6c.png">

Expected behavior is that the behavior would be the same – I suppose the widget's behavior is more technically proper, but the editor's is more user-friendly.

**Comment by irealva** [comment]
Peter I'm confused, I thought Tangram only supports CSS colors. So `lightblue` is a CSS color but `light blue` is not correct (I just tried it out in the developer console)?

**Comment by meetar** [comment]
I believe that officially, none of the css color names have spaces – and it turns out the spaces are being removed by the parser Tangram uses: https://github.com/deanm/css-color-parser-js/blob/master/csscolorparser.js#L132

**Comment by louh** [comment]
oh god

who is putting spaces in css color names

**Comment by meetar** [comment]
"light goldenrod yellow" just rolls off of the fingertips.

**Comment by irealva** [comment]
Still don't understand... why would we support `light blue` then?

**Comment by meetar** [comment]
Removing spaces is an easy way to cover all the cases when people accidentally put a space in. Leaving the spaces out of the color name is an unintuitive convention, and unless you work with those colors every day it's very easy to forget it should be that way. I forget all the time… at least I did until this thread, I'm probably less likely to forget now :)

**Comment by louh** [comment]
I'm going to leave my two cents here.

My understanding is that CSS color names _itself_ is a convenience for the Tangram scene author. @bcamper has noted before that his _preference_ is that we default to array formats for colors, like `[0, 1, 1]`, and in light of that note, I would presume that anyone preferring to using CSS color names are familiar with them. I therefore disagree with the claim that "leaving the spaces out of the color name is an unintuitive convention." I will add, as supporting evidence, that even browser vendors treat spaces in CSS color names as _invalid_, so scene authors should not be surprised that spaces in CSS color names ought to be invalid  _everywhere_.

At the same time, you are right to point out that as long as Tangram.js supports spaces in CSS color names, then we must, by extension, do the same. We are unfortunately locked to this particular vendor's implementation of CSS named colors.

As a related note to this, I should mention that the CSS parser library has not been updated in some time, so `rebeccapurple` (the only new named color in [CSS Color Module Level 4](https://drafts.csswg.org/css-color/) is not currently supported by Tangram, despite being valid in Play.

**Comment by louh** [comment]
An attempt to close that last gap in compatibility: https://github.com/deanm/css-color-parser-js/pull/4

**Comment by deanm** [comment]
💜
