### ISSUE TITLE
Dashed lines don't line up with indentation points

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-play#535]
![image](https://cloud.githubusercontent.com/assets/1190866/17874116/73095da2-687e-11e6-92f6-346fd36371d6.png)

The dashed line which you would expect to line up with 12 spaces lines up with 11. This is with Google Chrome 52.0.2743.116 (Official Build) m (64-bit) on Windows 8.1.

**Comment by louh** [comment]
Thanks @pnorman. This sometimes comes up randomly on Mac too, for reasons unknown. I'm leaving this open here but the priority for looking at this is pretty low.

**Comment by pnorman** [comment]
> I'm leaving this open here but the priority for looking at this is pretty low.

Ya - it's not a serious problem and by the time someone has enough indents for it to be an issue they're probably looking at using an external more powerful text editor anyways.

**Comment by louh** [comment]
@pnorman I haven't seen this problem again recently, have you? I'm wondering if has gone away on its own.

**Comment by pnorman** [comment]
> @pnorman I haven't seen this problem again recently, have you? I'm wondering if has gone away on its own.

I fit under the "using an external more powerful text editor anyways" class. I just tested, and it's fixed by something. I was getting it consistently, so I'm calling the bug fixed.
