### ISSUE TITLE
Browserify (and Babel?) for JavaScript organization

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#55]

**Comment by patriciogonzalezvivo** [comment]
What happen with the idea of using Browserfy?

**Comment by louh** [comment]
That's a typo! those keys are like, right next to each other.

**Comment by patriciogonzalezvivo** [comment]
: )

hehhee... don't worry I'm the king of typos = /

**Comment by patriciogonzalezvivo** [comment]
@louh, we need to add this CSS to the gulp css 

 
    <link type="text/css" rel="stylesheet" href="src/js/vendor/codemirror/css/codemirror.css">
    <link type="text/css" rel="stylesheet" href="src/js/vendor/codemirror/addon/fold/foldgutter.css">
    <link type="text/css" rel="stylesheet" href="src/js/vendor/codemirror/addon/dialog/dialog.css">
    <link type="text/css" rel="stylesheet" href="src/js/vendor/codemirror/addon/hint/show-hint.css">

also codemirror apear in node_modules (wich seams correct) and not in vendor...

**Comment by patriciogonzalezvivo** [comment]
Fixed https://github.com/tangrams/tangram-play/commit/7f0c1af92da430c199f051698957a4a0449e1abd

**Comment by louh** [comment]
good catch!!

Try this, this should also work:

@import 'codemirror/lib/codemirror.css';
@import 'codemirror/addon/dialog/dialog.css';
@import 'codemirror/addon/fold/foldgutter.css';
@import 'codemirror/addon/hint/show-hint.css';

In theory, PostCSS @import also understands Node modules, like the require() syntax, it should be able to find the codemirror package in the correct path. Hopefully this works!

**Comment by patriciogonzalezvivo** [comment]
Great!
working on that

**Comment by patriciogonzalezvivo** [comment]
@louh the widgets don't always update their position after loading... any clue?

**Comment by louh** [comment]
@patriciogonzalezvivo the thing is I did not finish the widget logic because I wanted infrastructure in place to let me build it as classes first. So it is supposed to be broken and there are going to be additional new bugs because of the JS reorg. Either way we are going to have to write a bunch of new code -- this is expected. I can do it or you can, let me know what you prefer.

**Comment by louh** [comment]
I'm going to close this because this task is technically done
