### ISSUE TITLE
Mask and replace API keys

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#58]

**Comment by patriciogonzalezvivo** [comment]
Masking key done: https://github.com/tangrams/tangram-play/commit/220331cc5be9e24556642b11b26b3aaeacc28d2e

If it doesn't have key it use one that  I create for tangram-play. This happens while is loading the syle to tangram.js so the user actually don't see it

Now once we have a way to check for the user keys, we can replace them

**Comment by patriciogonzalezvivo** [comment]
@mjcunningham will ask about getting API-keys of a user.

So in the future when ppl can login, will erase all api-key that doesn't belong to that user and promote using their own keys.

**Comment by louh** [comment]
User login (along with data associated with their account, like API keys) are further down the line and will be tracked in #8 or elsewhere.

Currently, masking API keys only happens for a small "blacklist" of default Mapzen keys, only to discourage users from copy-pasting them and using them elsewhere. We should not automatically police sharing of all API keys until we are certain that is what we want to do, and it is a possible use case that one organization with many users will need access to a shared set of API keys. So currently we preserve any key that isn't in the blacklist. 

Closing this now.
