### ISSUE TITLE
Inspect pop-up should show `kind` (instead of `kind_detail`)

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-play#585]
We're showing the `kind_detail` field in the title bar of the inspect pop-up, but this should be `kind` instead of `kind_detail`.

E.g. in this case, it being a `major_road` is more important than it being `secondary`:

![screen shot 2016-10-21 at 2 23 14 pm](https://cloud.githubusercontent.com/assets/16733/19607770/0f3338fc-979a-11e6-9497-3114743fec80.png)

**Comment by louh** [comment]
Would it make sense to show that line as `kind (kind_detail)`? e.g. `Major Road (Secondary)`

**Comment by bcamper** [comment]
Yeah that's cool

**Comment by louh** [comment]
Done in https://github.com/tangrams/tangram-play/pull/587
