### ISSUE TITLE
select dropdown sticks with what ever had before

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#609]
I wrote `blend: overlay` and then change my mind and choose other blending modes... although is possible to change it the `check` symbol still is pointing to the original choice

![00](https://cloud.githubusercontent.com/assets/346914/20976549/d6c15412-bc70-11e6-8a77-df37d783cdad.gif)

**Comment by louh** [comment]
This should fix it, give it a try: https://precog.mapzen.com/tangrams/tangram-play/issue-609/?#11.2933/39.9369/-75.2453

**Comment by patriciogonzalezvivo** [comment]
👍
