### ISSUE TITLE
JS code style standard

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#61]
Do we have a JS style? Should we match tangram's .jshintrc & .editorconfig? cc @bcamper 

Not necessarily an endorsement for this project, but personally (and without other organizational oversight) my JS follows [Standard](https://github.com/feross/standard), just so you know where I'm coming from (such as lines where semi-colons drop off when I am writing in a hurry).

**Comment by bcamper** [comment]
Yes let's please match the other settings for the main tangram repo, just for simplicity's sake. I'm open to debating style changes as we move forward, but we should use the same.

**Comment by louh** [comment]
:+1:

I will migrate the Tangram JS settings over today, is this okay @patriciogonzalezvivo ? I'd like to do this sooner rather than later because we already have started to have commit "wars" on JS style recently (since we are just writing code according to personal preferences right now). But we can gradually make the code line up over time, not rewriting everything right now.

**Comment by patriciogonzalezvivo** [comment]
:+1: perfect!

**Comment by louh** [comment]
Oh hey, seems JSHint is [deprecating](http://jshint.com/docs/options/) a bunch of options that is purely about style and not about code health. Indent spacing for example seems to be ignored if I run jshint locally (version 2.8.0).
There is this: [JSCS](https://github.com/jscs-dev/node-jscs) which we can use in addition to JSHint.

cc @bcamper

**Comment by patriciogonzalezvivo** [comment]
I'm using this a lot https://github.com/airbnb/javascript (via @louh )

**Comment by bcamper** [comment]
I'm not sure I want to endorse Standard personally... I think trying to follow the style of Tangram makes sense for consistency. Though I am open to changes there too! But keeping both the same is ideal. @louh have you added JSCS here? I haven't looked closely but have considered adding to Tangram too.

**Comment by louh** [comment]
Hey @bcamper - yes, I added JSHint and JSCS, and in the spirit of keeping code style consistent within the Tangram organization, I've tried to set up JSCS to match how Tangram JS is written. I've already found instances where some of my first stab at those settings make no sense, so any other eyes on it would be super helpful.
