### ISSUE TITLE
"save" vs "save as"

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#637]
Two menu options
- Save - if already in Mapzen account, prompt to overwrite. If not, do the same as "save as"
- Save as - the same as current save menu option

Checklist for "Save over"
- [x] Display current scene information in confirmation modal
- [x] Overwrite thumbnail image (do not prompt new metadata for now)
- [x] Remember "last saved" metadata in Redux upon loading from Mapzen Scenes API
- [x] Updating a thumbnail on the server should also update the server in local state

Misc
- [x] (BUG) A save or save-as modal appears twice if opened after Sign-in

**Comment by louh** [comment]
@burritojustice Give this a try on staging https://dev.mapzen.com/tangram/play/

**Comment by burritojustice** [comment]
"save", "save-over" and "save as..." are looking good.
