### ISSUE TITLE
Add a 'What's new'/'Welcome to Play' alert screen on first load for new users

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#638]
Do we think this is two separate screens (depending on whether it's a new user or returning user) or the same screen that works for both?

**Comment by louh** [comment]
speaking with @souperneon today - yes, these is two separate screens. A new user will see the "Welcome to Tangram Play" screen with onboarding info and a returning user sees the changelog.

**Comment by louh** [comment]
This is now up on preview: https://dev.mapzen.com/tangram/play/

**Comment by louh** [comment]
Here are the two screens:

Welcome:

<img width="684" alt="screenshot 2017-01-25 14 20 58" src="https://cloud.githubusercontent.com/assets/2553268/22305432/8e7165c0-e309-11e6-968b-3a34ecc897ba.png">

As you can see it's 100% placeholder text but we can do anything we want here (including buttons and graphics).

What's new:

![screenshot 2017-01-25 14 23 24](https://cloud.githubusercontent.com/assets/2553268/22305444/9ac30cde-e309-11e6-98e6-80edd07d09f8.png)

The what's new page is special because its content is an HTML page that gets iframed in. It's located here: https://github.com/tangrams/tangram-play/blob/next/data/changelog.html

There's nothing special about that HTML so that makes the content very easy to edit, and allows people to make changes to copy without having to touch the rest of the application.

**Comment by kkowalsky** [comment]
That's great that it's so easy @louh, I think @souperneon might have some nice UI ideas but I think it's good. Maybe buttons for 'Get Started' and 'Learn More' on the welcome screen

**Comment by souperneon** [comment]
@kkowalsky let's deal with this one when we go over all UI copy

**Comment by kkowalsky** [comment]
here's the copy:

We are excited for the public beta release of Tangram Play, our GUI editor for designing maps in Tangram (https://mapzen.com/products/tangram/), our web map rendering software. Your use  of Play in its beta stage will help shape it to be a useful tool for web map design.

If you're new here, find out more about Tangram Play on the Mapzen blog (link). The Walkthrough ( ) gives a brief explanation of how to use the interface and get started with designing a map, whether you’re creating from a blank slate or using one of our Mapzen basemaps (https://mapzen.com/products/maps/). 

If you've been here before, welcome back! There are a few changes to the interface that are described in the new features section.

**Comment by kkowalsky** [comment]
copy for about screen:

Tangram Play version: v.0.1.0 
Tangram version: v0.11.7
Leaflet version: v1.0.2
CodeMirror version: v5.22.2

Tangram Play is an interactive text editor for creating maps using Mapzen’s Tangram (https://mapzen.com/products/tangram/). With Play, you can write and edit map styles in YAML and preview the changes live in the web browser. Start with one of Mapzen’s base maps or create your own style. View the Tangram Play source code on GitHub (https://github.com/tangrams/tangram-play/).

**Comment by souperneon** [comment]
Looks good! Two questions about the language-
'designing maps in Tangram' or 'designing maps with Tangram'
'web map rendering software' or 'web map rendering engine'

**Comment by kkowalsky** [comment]
editing both of my copy examples to use your suggestions @souperneon

**Comment by louh** [comment]
Sorry, I missed this conversation (we have stuff in so many places!)

I've tended to use "engine" to describe Tangram because you could possibly classify Tangram as a "rendering engine." Another appropriate word to use might be "library" (it's the word used in the Tangram README). I'm less inclined to use "software" -- it's very generic, and encompasses things like apps, which can give the wrong impression.

**Comment by louh** [comment]
I've updated the I've-never-been-here landing modal to look like this:

![screenshot 2017-02-03 12 52 19](https://cloud.githubusercontent.com/assets/2553268/22602053/9e360120-ea0f-11e6-9753-f890330c0950.png)

**Comment by kkowalsky** [comment]
I'm editing the copy above to reflect the changes you've requested @louh

**Comment by louh** [comment]
I was actually in the middle of taking a stab at some edits:

> We’re excited for the public beta release of Tangram Play, a text editor for working with Tangram, our web map rendering library. Your use of Play in its beta stage will help us improve our tools for web map design.

These were some of my rationales:

- we can use contractions to be friendlier
- it's a text editor - yes, it's interactive, it's got graphical widgets, but at its core it is for code
- it facilitates design but I didn't want to draw connections to design-specific software; also, avoid the repetition of "design" in each sentence
- remove one instance of "our" in the first sentence
- "library" over "software" as above
- wording of "help shape it to be a useful tool" implies it's not useful now
- also adjusted wording to imply improvement for Mapzen's ecosystem of tools in general (which can involve in this direction) rather than Play specifically

**Comment by kkowalsky** [comment]
love the conciseness @louh!

**Comment by souperneon** [comment]
Nice! Looks good. Two comments-
1. remove the word test. This is a beta stage of launch and not test to check viability or of our users.
2. We can use the same pattern we have for 'Ok' 'Cancel' buttons for the last button to separate helpful links from just closing the modal.

**Comment by louh** [comment]
@souperneon "text" or "test" ?

re: 2. the thing I was afraid of is that it would be too small in a standard button. But maybe we can try some other way to indicate separation?

**Comment by louh** [comment]
![screenshot 2017-02-03 13 24 18](https://cloud.githubusercontent.com/assets/2553268/22603117/15375a0e-ea14-11e6-8ba4-fa1a5de9fc86.png)

**Comment by souperneon** [comment]
What's New
<img width="596" alt="screen shot 2017-02-03 at 2 25 39 pm" src="https://cloud.githubusercontent.com/assets/6125224/22605173/adf35416-ea1c-11e6-8837-b204d3080993.png">

Make these two 'Continue' buttons the same
