### ISSUE TITLE
Reorganize example gallery

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#640]
Need-based classification (e.g. "base map display," "routing" etc) rather than "easy/simple/advanced" (also, rename "Patricio's greatest hits")

See classification list: https://github.com/tangrams/tangram-play/blob/master/src/js/modals/examples.json

Supercedes #320.

**Comment by kkowalsky** [comment]
Recommendations:

1. Condense Grain into 1 example with area & roads added to 1 section
2. Remove 'Patricio's Greatest Hits' 
3. Edit House styles to use the import: .zip and hide 409485935 lines of YAML
4. Add Tutorial and @rfriberg blog examples

**Comment by louh** [comment]
Following up with a summary of the discussion on point 3 after today's standup:

We have two theoretical user groups for the "zip import" format vs the "full yaml" format - both have different priorities and a different set of tradeoffs.

When we make the entire YAML available for a house style, we're catering to a user who appreciates seeing source code and wants to know how the sausage is made, who wants to be able to examine it, take it apart and put it back together into their own scene. This is extremely overwhelming for someone who "just wants a base map."

When we display a single import to a zip and expose none of the internals, we give a different type of user a pristine canvas (just the base layer) upon which they can overlay their own data, visualizations, etc.  But in this way, the imported house style is a complete black box, and can be just as frustrating because we offer no clue where to start. We're not launching with multiple-tab support (there are still too many broken edge cases to work through) so there is not an easy way to inspect the internals of a house style.

There is a potential "missing middle" here. One solution to meet that middle is a scene that imports the house style but exposes some of the configuration that users might care about tweaking, with additional guiding comments. This would require some work from the Cartography team, and perhaps some research about which variables we expose and how we explain them.

In the meantime, replacing the "source" versions of house styles with "blank import" versus of house styles is replacing one set of priorities with a different set of priorities, and in my estimation, one is not inherently better than the other, so rather than there being a net gain, we just replace one set of problems with another (and solve neither). They are also not mutually exclusive. If we name them and sort them appropriately, we can still have both available.

As we conduct user research post-launch, we will have a much better idea of what proportion these user groups exist in, and that can direct future prioritization for either approach.

I hope that summarizes appropriately (at least for me!)

**Comment by souperneon** [comment]
Bubble Wrap
A full-featured wayfinding style loaded with helpful icons for points of interest. 

Cinnabar
A classic web map style for general mapping applications.

Cinnabar (no labels)
A classic web map style for general mapping applications.

Cinnabar (more labels)
A classic web map style for general mapping applications.

Refill
A light, minimalist map style designed for data visualization overlays.

Refill (no labels)
A light & minimalist map style designed for data visualization overlays.

Refill (more labels)
A light & minimalist map style designed for data visualization overlays.

Zinc
A dark, minimalist style that helps bright data overlays stand out. 

Walkabout
This outdoor style is perfect for hiking or getting out and about, with mountains, ski trails, biking paths, and transit stops.

Walkabout (no labels)
This outdoor style is perfect for hiking or getting out and about, with mountains, ski trails, biking paths, and transit stops.

Walkabout (more labels)
This outdoor style is perfect for hiking or getting out and about, with mountains, ski trails, biking paths, and transit stops.

Tron (animated)
Pushing mapping to new extremes with a movie inspired style with animation and lots of neon.

Matrix (animated)
Aren't we all Neo's wandering this planet? Another movie inspired animated style.

**Comment by kkowalsky** [comment]
@nvkelso and I discussed this IRL and think that using the the import zip bundles might work to streamline the concerns about overwhelming house styles. Using some of @meetar and @rfriberg's house style tweaking in the example commented out could serve as a way to compromise.

@souperneon I'm worried about having the multiple options for no/more labels as being too much. I recommend a link to the cartography docs for this.

**Comment by kkowalsky** [comment]
// erroneous thoughts
- for using the full YAML files, can we remove some of the comments in the basemaps? There are debugging things in Bubblewrap lines 759-817 making things gross. We might consider creating a separate version of the Major releases to not have these, just for Tangram Play?
- glorious future request is to have collapsible lines of code on load for the house styles
- v2 option would have  a slider for how many labels you want the basemap option to have
//

Here are @souperneon & I's plan for launch:
- Have 'New Blank Scene' open empty.yaml (but rename this to match and be blank.yaml) 
- Make the first option from 'new scene from example' be a new scene file similar to Default but w/o blocks named Basic (basic.yaml)
- Have the 6 house styles underneath with some of the editing mentioned above with Ekta's copy 
- Remove Patricio's Greatest Hits

**Comment by louh** [comment]
@kkowalsky for the section labeled "erroneous thoughts" can you break these out in to separate issues? thanks!

**Comment by louh** [comment]
Closing due to inaction on extending the list of examples; also, the ability to categorize scenes have been removed in a recent refactor to consolidate "open scene modals" code. We can revisit this again when we have more examples to add. Any other issues pertaining to the contents and readability of individual examples should be tracked as separate issues.
