### ISSUE TITLE
support plan

### ISSUE THREAD

**Issue by kkowalsky** [tangrams/tangram-play#646]
There are a few parts to this, but one pressing concern is that I'm on vacation during launch. This means @rmglennon will have to monitor any support q's and send them over to the appropriate channels. I recommend using a tangram@mapzen.com email for contact during launch that can CC @louh and get any requests handled immediately.

**Comment by louh** [comment]
Who is in charge of making email addresses for Mapzen?

**Comment by kkowalsky** [comment]
@mjcunningham, lets make one (or bring it into Zendesk if it exists already)

**Comment by mjcunningham** [comment]
there is an old tangram@ alias which seems to just be @bcamper and @meetar.

I can point this to zendesk or just add Lou. Thoughts?

**Comment by meetar** [comment]
Either solution is fine with me :+1:

**Comment by kkowalsky** [comment]
![both](https://cloud.githubusercontent.com/assets/4246770/22272436/d9788578-e24e-11e6-8bf5-729621d4b49f.png)

**Comment by meetar** [comment]
:) I'd prefer a single entry point for support requests, to prevent
multiple uncoordinated responses – in fact I think we have more Tangram
requests coming through zendesk now, so the tangram@ alias should probably
just point there.

**Comment by mjcunningham** [comment]
ok now tangram@ paints to zendesk.

**Comment by louh** [comment]
Add me to zendesk?

**Comment by mjcunningham** [comment]
@rmglennon is the CEO of Zendesk.

**Comment by rmglennon** [comment]
OK, while @kkowalsky is out, @louh can be swapped in (we have limited support accounts).

**Comment by louh** [comment]
:+1: ah ok, didn't know about the limits. works for me!

**Comment by kkowalsky** [comment]
wow that'll force me to **actually** have a great vacation :smile:
