### ISSUE TITLE
Scrub the UI for copy 

### ISSUE THREAD

**Issue by souperneon** [tangrams/tangram-play#652]
Make sure all the pop ups and menu items have consistent and understandable language and tie-up with documentation

**Comment by souperneon** [comment]
@kkowalsky did you transfer all the UI menu and button copy changes to a ticket somewhere? It lives in the walkthrough doc that you are working on

**Comment by kkowalsky** [comment]
oh my bad @souperneon I was confused about this ticket and whether we finished it during standup. reopening.

**Comment by souperneon** [comment]
**Menus**
New

- New blank scene
- New from example…

Open

- Open scene…
- Open scene from Mapzen account…
- Open from URL…

Save

- Download
- Save (Mapzen account)
- Save as…

Share

- Get hosted link
- Get embed code

Help

- About
- What's new
- Documentation
- Support

**Comment by kkowalsky** [comment]
LGTM, @louh I think there's very minimal copy changes but a few here

**Comment by louh** [comment]
@souperneon I tried some pretty different text under "Share" - have you seen this yet? Should we revise this or go back to the old text? For "Get embed code" in particular, I wanted to try something that output more code than an HTML `iframe` tag.

![screenshot 2017-02-03 13 56 26](https://cloud.githubusercontent.com/assets/2553268/22604231/929ca22a-ea18-11e6-8828-04454b92d9bd.png)

**Comment by louh** [comment]
Closing now since everything specific in this issue should be addressed
