### ISSUE TITLE
Rename Feedback to Support

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#657]
Support links to ... ?

**Comment by louh** [comment]
Alert popup
- Email tangram@mapzen.com
- GitHub issue

**Comment by kkowalsky** [comment]
copy:

## Tangram Play Support:
Learn more about using Tangram (https://mapzen.com/documentation/tangram) and Mapzen vector tiles (https://mapzen.com/documentation/vector-tiles/) on their documentation pages. 

Having a problem with Tangram Play? Do you have feedback to share? Contact Mapzen Support by emailing tangram@mapzen.com (mailto:tangram@mapzen.com ). 

Tangram Play is still in active development and you can have a role in it! Add bugs or feature requests as an issue on the project’s GitHub Repository here (https://github.com/tangrams/tangram-play/issues).

**Comment by louh** [comment]
Added 550f69763c2768c199994fa7484cf5eadd1d5960
