### ISSUE TITLE
BUG: api_key value stripped from url params for Mapzen basemap styles

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-play#663]
This is related to Tangram Frame (view), but the root cause seems to be in Tangram Play so filing here.

When viewing the following in Tangram Play network request show the api_key is correctly set to the value in the imported scene file:

```
import: https://mapzen.com/carto/refill-style/6/refill-style.zip

global:
  sdk_transit_overlay: true
```

But when using the YAML import it strips the set API key and instead swaps in a new one:

```
import: https://mapzen.com/carto/refill-style/6/refill-style.yaml

global:
  sdk_transit_overlay: true
```

The problem then is when I view the ZIP based file in Tangram Frame it works, but when I view the YAML based file in Tangram Frame it mostly doesn't work because the API key is set to '' resulting in 429 rate limiting.

API key stripped (bad!!!):

- https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/22/164/resources/empty.yaml#13.5505/38.1314/13.3575

API not stripped:

- https://mapzen.com/tangram/view/?scene=https://mapzen.com/api/scenes/506/178/resources/scene.yaml#4/14.94/-71.02

**Comment by louh** [comment]
Hi @nvkelso,

I see in https://mapzen.com/carto/refill-style/6/refill-style.yaml that `sdk_mapzen_api_key: ''` (It is blank there). Tangram Play does not strip pre-existing API keys, it is replacing it, because it is blank in that file.

Tangram Frame does not inject keys at the moment, so the API key is blank, as expected.

**Comment by nvkelso** [comment]
Verified, that looks like a release management problem for me to solve :\

**Comment by nvkelso** [comment]
This is fixed on prod on `mapzen.com/carto`.
