### ISSUE TITLE
add links on Tangram Product Page to Play

### ISSUE THREAD

**Issue by kkowalsky** [tangrams/tangram-play#667]
assigning to @souperneon

**Comment by souperneon** [comment]
@kkowalsky would love some more detail here, where were you thinking specifically?

**Comment by kkowalsky** [comment]
1. let's replace all of the "check out the code" links under examples to open in Play. 
2. under 'get started' let's add copy about Tangram Play

**Comment by kkowalsky** [comment]
day/night: https://mapzen.com/tangram/play/?scene=https://raw.githubusercontent.com/tangrams/carousel/gh-pages/styles/daynight.yaml#15.8163/40.7408/-73.9828

cinnabar: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fmapzen.com%2Fcarto%2Fcinnabar-style%2Fcinnabar-style.yaml

crosshatch: https://mapzen.com/tangram/play/?scene=https://raw.githubusercontent.com/tangrams/tangram-sandbox/gh-pages/styles/crosshatch.yaml

tron: https://mapzen.com/tangram/play/?scene=https://raw.githubusercontent.com/tangrams/tron-style/gh-pages/tron-style.yaml

imhof: https://mapzen.com/tangram/play/?scene=https://raw.githubusercontent.com/tangrams/carousel/gh-pages/styles/imhof2.yaml#11.2663/37.8316/-122.4267

**Comment by souperneon** [comment]
@louh can I get your help on this?

**Comment by louh** [comment]
We still need to add something to the /products/tangram page

**Comment by louh** [comment]
![screenshot 2017-02-07 11 08 11](https://cloud.githubusercontent.com/assets/2553268/22699528/bd4267b6-ed25-11e6-8427-50b0f6244f3d.png)
