### ISSUE TITLE
Tangram map occasionally fails to draw inside an embed

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#671]
On https://precog.mapzen.com/mapzen/documentation/meetar/tutorial-divs/documentation/tangram/custom-styles/ :

To replicate:

- scroll until the editor loads in another demo pane
- repeat until one of the maps fails to draw. (My record is 2 loads.)

When this happens, no error is thrown, _until_:

*Result 1:*

Typing in the editor, hitting the "reload" button, or switching to another tab and then back throws this error:

```
VM4525 tangram.min.js:18 Uncaught (in promise) TypeError: Cannot read property 'error' of undefined
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3515
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at https://mapzen.com/tangram/0.11/tangram.min.js:12:8453
```

*Result 2:*

If you click the leaflet zoom buttons, this error is thrown:

```
VM4527 embedded.js:23 Tangram v0.11.7 [warn]: Caught exception in listener for event 'move': TypeError: Cannot read property 'move' of undefined
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3515
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at Object.move (https://mapzen.com/tangram/0.11/tangram.min.js:12:24497)
    at https://mapzen.com/tangram/0.11/tangram.min.js:18:3528
    at Array.forEach (native)
    at e.trigger (https://mapzen.com/tangram/0.11/tangram.min.js:18:3472)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:18:28159)
    at e.value (https://mapzen.com/tangram/0.11/tangram.min.js:18:26559)
    at t.hooks.move (https://mapzen.com/tangram/0.11/tangram.min.js:11:2326)
    at t.fire (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:14:16162)
    at t._move (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:12274)
    at t._onZoomTransitionEnd (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:19238)
    at t._catchTransitionEnd (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:18280)
    at HTMLDivElement.l (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:15:22501)
    at HTMLDivElement.r (https://precog.mapzen.com/tangrams/tangram-play/master/build/js/embedded.js:23:10780)
```

… I think this just means the map isn't there. But I can't tell why.

The code on this page (https://github.com/mapzen/documentation/edit/meetar/tutorial-divs/src-tangram-new/custom-styles.md) is just moving the same iframe around and changing its `src` – which _should_ be the same as loading any other new browsing context. And in this case afaik my "hidey code" isn't doing anything fancy… just moving the iframe and changing its `src`.

**Comment by bcamper** [comment]
It's a Tangram error, so it's likely not Play's issue directly. I wonder if
it is a problem with event handlers from a previous scene/map that aren't
being unloaded (and trying to call a map that no longer exists).

**Comment by bcamper** [comment]
@meetar for the second example, can you try this with a tangram debug build and set a breakpoint here:

https://github.com/tangrams/tangram/blob/master/src/utils/subscribe.js#L33

We could be checking for the existence of these objects to avoid this specific error, but the fact it's happening indicates something probably isn't being cleaned up properly.

**Comment by meetar** [comment]
@bcamper Unfortunately this problem doesn't manifest locally so I don't
think I can test that :/

There's no sneaky way to specify a specific/custom/local build of tangram
for Play to use, is there @lou ?

**Comment by bcamper** [comment]
No but it's a feature we need!! :)

**Comment by louh** [comment]
I'm glad you're putting it this way, because I was originally thinking that changing the Tangram build is a "Tangram Play feature for everybody" but the better idea is to make it a internal-use-only override of the Tangram library. It simplifies a ton of things. Is it OK if I try this on a separate branch before merging anything to master?

**Comment by bcamper** [comment]
👍

**Comment by louh** [comment]
OK, something like this:

https://precog.mapzen.com/tangrams/tangram-play/tangram-override/?lib=https:%2F%2Flocalhost:8080%2Ftangram.debug.js#11.2933/39.9369/-75.2456

At the moment it's hosted on Precog, which forces HTTPS, meaning you have to put your debug build behind an HTTPS or you'll hit a mixed-content warning. If you really don't want to do that, I can trigger a deploy of this branch to the dev server which can be accessed over HTTP.

I've intentionally kept this dead simple with minimal logic, so it differs from Tangram Frame in that you must set a full URL to the library (it still checks whether it's hosted by Mapzen or localhost to prevent shady behavior) - there is no special parsing of version numbers or builds, and there is nothing in Play that assumes it's using anything other than the latest version of Tangram, so other bugs can result. Those are your caveats!



I will be intentionally keeping it dead simple: full URL to the library ONLY, (no special parsing for version numbers/builds), and the Leaflet version will not change. Tangram Play may be depending on features from the latest version of Tangram, so use at your own risk.

**Comment by bcamper** [comment]
I think this is a good balance. How would this work with possible future
bundling of Tangram? Does that actually pose a problem here?

**Comment by louh** [comment]
In a situation where arbitrary Tangram dependencies may be loaded, it won't make sense to bundle.

**Comment by louh** [comment]
The behavior on the `tangram-override` branch has been updated to provide a convenience `?debug=true` flag whose only purpose is to load the `tangram.debug.js` version of the normal library, since debugging the current version of Tangram is likely to be the most common use case. `debug=true` and `lib=${your_url}` cannot be used concurrently (`lib=` takes priority, and `debug=true` does not alter the URL provided in `lib=`).

**Comment by louh** [comment]
@meetar did we resolve this or take a different approach to get around this?

**Comment by meetar** [comment]
Yes, this has been obviated.
