### ISSUE TITLE
Inspection modal is placed out-of-view until the map zoom changes

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-play#672]
Tested in Firefox 51.0.1 and Chrome 55.0 on macOS 10.11.6

Steps to reproduce:
  1. Enable the "Inspect" button.
  2. Mouse over a map feature (a small box with the feature type will appear)
  3. Click on the feature (the map will pan to center on the feature and the small box will disappear)
  4. Zoom the map in or out by any amount (the inspection modal will animate to the correct position)

**Comment by louh** [comment]
Is this still a problem on the staging server? https://dev.mapzen.com/tangram/play/

We fixed a bug that sounded very much like this in https://github.com/tangrams/tangram-play/issues/654

**Comment by matteblair** [comment]
Oh yup it's fixed in staging, carry on!
