### ISSUE TITLE
'You have unsaved changes' message remains after making a save

### ISSUE THREAD

**Issue by skorasaurus** [tangrams/tangram-play#678]
Hi, 

While using tangram-play just now, I noticed that the 'you have unsaved changes' message still appears after you save a scene (and before you make any additional modifications to the YAML/scene). I can confirm that the scene is being successfully changed in tangram-play to my mapzen account. 

To replicate: 

1. Open an existing scene or create a new scene in your account. 
2. Make any change in the yaml scene file. 
3. click save (confirm that you want to overwrite the saved scene, if applicable). 
4. message that you have unsaved changes is still appearing. 

(Using Firefox 51.0.1, ubuntu 64-bit).  
Here's a video of the action as well - https://dl.dropboxusercontent.com/u/17003223/mapzen_error.ogv

**Comment by louh** [comment]
Thanks for the really clear report, @skorasaurus. I'll be looking into it in the next few days!

**Comment by louh** [comment]
This should be fixed and deployed now!
