### ISSUE TITLE
embedded editor doesn't appear in Safari 8.0.7

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram-play#681]
Reported by @nvkelso 

https://files.slack.com/files-pri/T065YL1LH-F46BCLTAT/pasted_image_at_2017_02_15_12_06_am.png

Seen at https://precog.mapzen.com/mapzen/documentation/meetar/tutorial-divs/documentation/tangram/custom-styles/

**Comment by louh** [comment]
The screenshot isn't appearing.

Also, is there a reason why we're not using the latest version of Safari?

**Comment by meetar** [comment]
Here's the screenshot: ![pasted_image_at_2017_02_15_12_06_am](https://cloud.githubusercontent.com/assets/459970/23096872/db2286d6-f5f3-11e6-86db-bd24b24fffef.png)

> Also, is there a reason why we're not using the latest version of Safari?

Unknown, probably entropy.

**Comment by louh** [comment]
The front-end team is setting minimum browser support to "latest" for all browsers except for IE, so we're officially not going to pursue bug fixes in old versions of Safari.
