### ISSUE TITLE
Colors don't tween

### ISSUE THREAD

**Issue by nspringer-alk** [tangrams/tangram-play#739]
Color arrays should tween between levels.  

Given this example: `color: [ [ 0, "#d9d9d0" ], [ 10, "#d9d9d0" ], [ 11, "#dbd9cc" ], [12, "#ffffff"]]`

At zoom 1.5 the color should be halfway between #dbd9cc and #ffffff

**Comment by louh** [comment]
Hey @nspringer-alk -- I checked in with the Tangram team who confirms that the tweens only happen at integer zooms. There is some explanation about it in this issue [here](https://github.com/tangrams/tangram/issues/530). One suggestion from there might be to use a shader, which has access to the fractional zoom value.
