### ISSUE TITLE
provide a method to share a URL to open a scene file in Play

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram-play#744]
Before the tangram-view URL and API schema was updated, you could easily open a scene in Tangram Play by swapping out `/view` for `/play`.

The new shorter URL for sharing maps is awesome, we lost the ability to easily share scenes in Tangram Play.

While I can dig into the console and get the scene URL and append it to `https://mapzen.com/tangram/play/?scene=` this is... suboptimal.

Whether it is letting a user swap `/view` for `/play` in the new URL, or providing a method of sharing a URL that will open up Play in the existing share map and code UI, a way to readily share URLs that open up in Play would be very helpful.

**Comment by bcamper** [comment]
I'd classify this as a high priority issue. It's making it rather difficult to debug issues submitted with links to `view`.

@louh what's the effort level here and/or is there some temporary fix we can employ?

**Comment by louh** [comment]
It shouldn't be super difficult, but I haven't switched my mental context to Tangram Play for a while. I won't get to it today, and make no guarantees for the rest of the week, but I'll keep it in mind.

**Comment by bcamper** [comment]
Does the old view behavior still work? In the meantime I suggest we reframe from using the `api=` syntax, because this has actually impacted work in a noticeable way.

**Comment by louh** [comment]
OK, I shoehorned in some `?api=` functionality. Clear your Tangram Play cache and try this to see if it's working:

https://mapzen.com/tangram/play/?api=7/26#9.5759/40.7253/-74.1394

you should see a puke green map.

Note that this circumvents a normal initialization path so highlighted lines _do not work_ right now.  But I assume you don't have those from `/view` anyway.

@burritojustice If you want to see a button or link  or something from `/view` that goes into Tangram Play please file that request over at github.com/tangrams/tangram-frame. I am closing this issue.

**Comment by burritojustice** [comment]
\o/ ![image](https://user-images.githubusercontent.com/3979711/29379625-ee58eee6-8277-11e7-8401-b54fed2d4098.png) 

thanks, Lou
