### ISSUE TITLE
malformed name from geocoder (minor UTF issue)

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-play#747]
Search bar, as one moves around is populated by current location

Sometimes current location contains UTF8 characters.

Sometimes UTF8 characters are malformed

For example "NowosÄdecki, Poland" instead of "Nowosądecki, Poland" on browsing around https://mapzen.com/tangram/play/?#8.5000/49.5247/20.9499

Issues is not causing any noticeable problems beyond something surprising for no good reason and potentially confusing.

**Comment by louh** [comment]
Hey @matkoniecz, thanks for the report. The underlying data from the geocoder seems to be coming from this data source: https://whosonfirst.mapzen.com/spelunker/id/102079425/

We can't fix it here, but I'll see if I can forward this report upstream to the data brokers.
