### ISSUE TITLE
it is not clear how one may add additional files

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-play#751]
For example, I would like to add .svg file with icons (from Cinnabar) so I will be able to display icons on a map (as file is not added I currently get "failed to load texture...").

**Comment by bcamper** [comment]
Hi -- Tangram Play does not currently support uploading files (or editing multiple YAML files for one scene). You can however upload these assets to any https-accessible server (S3 etc.) and access them via Tangram Play (though you will need [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) enabled).

**Comment by skorasaurus** [comment]
@matkoniecz 

You can also upload them via github, just be sure to use the raw... url instead of the 

for example, you can plop this in tangram play and it'll load - https://raw.githubusercontent.com/skorasaurus/sc3n3/master/pericoli.yaml
