### ISSUE TITLE
Uncaught TypeError after colorpicker interaction

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#76]

**Comment by patriciogonzalezvivo** [comment]
Click on a color button... interact with the color picker and then click on the map.

You get something like this in the console:

Uncaught TypeError: Cannot read property 'classList' of null(anonymous function) @ ui.js:44

**Comment by louh** [comment]
My fault, it is related to a quick hack to close a dropdown menu if you click outside of it. I've been meaning to fix that...!
