### ISSUE TITLE
Font picker ideas

### ISSUE THREAD

**Issue by souperneon** [tangrams/tangram-play#86]
http://lindekleiv.bitbucket.org/fontselector/

This has a list of Google fonts which will be nice to have as options. Can we work that in?

**Comment by patriciogonzalezvivo** [comment]
Mmmmmm... no JQuerry.... is a huge library. : S
Also we can not do Google Fonts for the moment. Has to be something that use the Web Safe Fonts ( http://www.w3schools.com/cssref/css_websafe_fonts.asp )

**Comment by louh** [comment]
What's the reason for the requirement to use web safe fonts?
Secondly, is this considered a high priority feature? (You would have to convince me... :P)

**Comment by patriciogonzalezvivo** [comment]
hehe Definitely not high priority now, but soon... Ekta was doing some research while the core was getting more mature. Soon we will start working more in the UI and we were thinking the importance of having a homogeneous and consistent set of widgets and pickers. 

Unfortunately we can not do non-safe-fonts for the moment and tangram. But labels are getting some traction. Mayor features will be injected in the upcomming month. With Geraldine and Nathaniel on board labels and fonts will become important.

**Comment by louh** [comment]
OH, I totally misunderstood this. I thought it was a font picker for the editor :)
Duh, labels. This makes much more sense now.
