### ISSUE TITLE
CSS style

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#88]

**Comment by patriciogonzalezvivo** [comment]
@louh we should try to come to a common nomenclature for DOM classes and Id... to be sure they will not colide with something else: I start using the preposition "tangram-play-"

https://github.com/tangrams/tangram-play/blob/gh-pages/src/css/_suggest.css
https://github.com/tangrams/tangram-play/blob/gh-pages/src/css/_widgets.css

Maybe we can separe between "code" and "addons" doing something like  ```tangram-play-*```  ```tangram-play-addon-*```. For example: ```tangram-play-map```,  ```tangram-play-editor```,  ```tangram-play-divider```,  ```tangram-play-addon-menu```, ```tangram-play-addon-suggest-menu```, ```tangram-play-addon-widgets```,  ```tangram-play-addon-widgets-colorpicker``` , ```tangram-play-addon-widgets-dropdown```, etc

**Comment by louh** [comment]
That tends to create _really_ long names, and it becomes very unwieldy.

If we did a shorter preposition like `tp-*` instead it would be much easier to write.

It would also be helpful not to assume too much hierarchy in the naming convention. A prefix like `-addon-` to make a class `-addon-widgets` isn't that much more useful if we assume that there's no other _kind_ of widgets, for example, so `tp-widgets` is still fundamentally the same in meaning as `tp-addon-widgets`. 

Altogether, `tp-suggest-menu` is much simpler and easier to manage than `tangram-play-addon-suggest-menu`.

Lastly - I would suggest keeping the CSS source files themselves clean and using a PostCSS plugin to apply a common prefix. See here: https://github.com/thompsongl/postcss-class-prefix/

**Comment by patriciogonzalezvivo** [comment]
You are right ```tp-*``` makes more sense. I'm still think we need to separate addons in some way to make the project scalable and modular and keep everthing clean, what do you think about ```tp-a-[addon-name]-*``` for addons.

**Comment by louh** [comment]
Let me think about this. But here is my hunch / argument: I think the separation should be in the file structure, but in class naming, flatter hierarchy is better. We can re-organize hierarchy in files without changing much code. But reorganizing hierarchy in class names requires potentially doing a lot of search-replace on code in the future.

**Comment by louh** [comment]
On second thought, it is probably best / clearer not to append a `.tp-*` prefix via script -- I'm going to do that by hand, so it's easier to incrementally refactor.
