### ISSUE TITLE
Keypress manager

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#94]
https://craig.is/killing/mice
Makes it easy to bind actions to common shortcut keys.

**Comment by patriciogonzalezvivo** [comment]
This is for non-CodeMirror hotKeys? Codemirror has it own event handler that we can hook to it if we want

**Comment by louh** [comment]
Entirely for UI outside of CodeMirror  - for instance, pressing "escape" while a modal is open should be equivalent to cancelling that interaction. However, there are probably some instances where a menu item that touches CM (like open / save file) also has a shortcut key too. If CM has a way to listen for keydown events outside of CM (like someone presses Ctrl-S to save, while the user is focused on the map) then that would work, we wouldn't need an external library. (That is a bad example, Leaflet tends to gobble up events, so it might not work anyway)

**Comment by patriciogonzalezvivo** [comment]
Did we move forward with this?

**Comment by louh** [comment]
So far I have just been writing my own listeners for keypresses on individual UI elements.

**Comment by louh** [comment]
Closing this; we have not needed to implement this but we will know if and when this is important!
